// Generated by gencpp from file bumperbot_example/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BUMPERBOT_EXAMPLE_MESSAGE_ADDTWOINTS_H
#define BUMPERBOT_EXAMPLE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <bumperbot_example/AddTwoIntsRequest.h>
#include <bumperbot_example/AddTwoIntsResponse.h>


namespace bumperbot_example
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace bumperbot_example


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bumperbot_example::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::bumperbot_example::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::bumperbot_example::AddTwoInts > {
  static const char* value()
  {
    return "bumperbot_example/AddTwoInts";
  }

  static const char* value(const ::bumperbot_example::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::bumperbot_example::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::bumperbot_example::AddTwoInts >
template<>
struct MD5Sum< ::bumperbot_example::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bumperbot_example::AddTwoInts >::value();
  }
  static const char* value(const ::bumperbot_example::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bumperbot_example::AddTwoIntsRequest> should match
// service_traits::DataType< ::bumperbot_example::AddTwoInts >
template<>
struct DataType< ::bumperbot_example::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::bumperbot_example::AddTwoInts >::value();
  }
  static const char* value(const ::bumperbot_example::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bumperbot_example::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::bumperbot_example::AddTwoInts >
template<>
struct MD5Sum< ::bumperbot_example::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bumperbot_example::AddTwoInts >::value();
  }
  static const char* value(const ::bumperbot_example::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bumperbot_example::AddTwoIntsResponse> should match
// service_traits::DataType< ::bumperbot_example::AddTwoInts >
template<>
struct DataType< ::bumperbot_example::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::bumperbot_example::AddTwoInts >::value();
  }
  static const char* value(const ::bumperbot_example::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUMPERBOT_EXAMPLE_MESSAGE_ADDTWOINTS_H
