// Generated by gencpp from file bumperbot_example/GetTransform.msg
// DO NOT EDIT!


#ifndef BUMPERBOT_EXAMPLE_MESSAGE_GETTRANSFORM_H
#define BUMPERBOT_EXAMPLE_MESSAGE_GETTRANSFORM_H

#include <ros/service_traits.h>


#include <bumperbot_example/GetTransformRequest.h>
#include <bumperbot_example/GetTransformResponse.h>


namespace bumperbot_example
{

struct GetTransform
{

typedef GetTransformRequest Request;
typedef GetTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTransform
} // namespace bumperbot_example


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bumperbot_example::GetTransform > {
  static const char* value()
  {
    return "cd915af3643e080e81d0d0cf82efa933";
  }

  static const char* value(const ::bumperbot_example::GetTransform&) { return value(); }
};

template<>
struct DataType< ::bumperbot_example::GetTransform > {
  static const char* value()
  {
    return "bumperbot_example/GetTransform";
  }

  static const char* value(const ::bumperbot_example::GetTransform&) { return value(); }
};


// service_traits::MD5Sum< ::bumperbot_example::GetTransformRequest> should match
// service_traits::MD5Sum< ::bumperbot_example::GetTransform >
template<>
struct MD5Sum< ::bumperbot_example::GetTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bumperbot_example::GetTransform >::value();
  }
  static const char* value(const ::bumperbot_example::GetTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bumperbot_example::GetTransformRequest> should match
// service_traits::DataType< ::bumperbot_example::GetTransform >
template<>
struct DataType< ::bumperbot_example::GetTransformRequest>
{
  static const char* value()
  {
    return DataType< ::bumperbot_example::GetTransform >::value();
  }
  static const char* value(const ::bumperbot_example::GetTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bumperbot_example::GetTransformResponse> should match
// service_traits::MD5Sum< ::bumperbot_example::GetTransform >
template<>
struct MD5Sum< ::bumperbot_example::GetTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bumperbot_example::GetTransform >::value();
  }
  static const char* value(const ::bumperbot_example::GetTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bumperbot_example::GetTransformResponse> should match
// service_traits::DataType< ::bumperbot_example::GetTransform >
template<>
struct DataType< ::bumperbot_example::GetTransformResponse>
{
  static const char* value()
  {
    return DataType< ::bumperbot_example::GetTransform >::value();
  }
  static const char* value(const ::bumperbot_example::GetTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUMPERBOT_EXAMPLE_MESSAGE_GETTRANSFORM_H
